language: java

# see https://github.com/softwaresaved/build_and_test_examples/blob/master/travis/Languages.md
jdk:
  - oraclejdk8
#  - openjdk8 # disabled, does not exist: https://github.com/travis-ci/travis-ci/issues/6483

# coveralls plugin
# https://github.com/kbase/project_guides/blob/master/Setting_up_Travis_CI_and_Coveralls.md
# https://github.com/trautonen/coveralls-maven-plugin

after_success:
  - coveralls
